# Add shared library versions here if needed, e.g.:
[versions]
kotlin = "2.3.10"                   # Kotlin plugin version
shadow = "9.3.1"                    # Shadow plugin version
paper = "1.21.11-R0.1-SNAPSHOT"     # Paper server software version
bukkit-factory = "1.3.1"            # resource-factory plugin version
run-paper = "3.0.2"                 # run-task plugin version
bstats = "3.1.0"                    # bstats dependency version
boosted-yaml = "1.3.7"              # boosted-yaml dependency version

# Add shared libraries here if needed, e.g.:
[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
boosted-yaml = { module = "dev.dejvokep:boosted-yaml", version.ref = "boosted-yaml" }

# Add shared plugins here if needed, e.g.:
[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
bukkit-factory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "bukkit-factory" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
